# GitLab CI/CD configuration

# Define stages
stages:
  - docker_compose
  - build_rust
  - test

# Docker Image CI job
Docker_Image_CI:
  stage: docker_compose
  image: ubuntu:latest
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled # Enabling Docker experimental CLI features
  before_script:
    - apt-get update -y
    - apt-get install -y docker.io docker-compose python3-distutils
  script:
    - docker-compose up -d

# Rust job
Rust:
  stage: build_rust
  image: rust:latest
  script:
    - cargo build --verbose

# Run tests job
Run_tests:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
