# GitLab CI/CD configuration

# Define stages
stages:
  - build_docker_image
  - build_rust
  - test

# Docker-in-Docker service
services:
  - docker:dind

# Docker Image CI job
Docker_Image_CI:
  stage: build_docker_image
  script:
    - docker build . --file Dockerfile --tag my-image-name:$(date +%s)

# Rust job
Rust:
  stage: build_rust
  image: rust:latest
  script:
    - cargo build --verbose

# Run tests job
Run_tests:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
