stages:
  - docker_build
  - build_rust
  - build_release_rust
  - test_rust

variables:
  # Rust CI
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

docker-build:
  stage: docker_build
  image: docker
  script:
    - docker build . --file Dockerfile --tag my-image-name:$(date +%s)

build:
  stage: build_rust
  image: rust:latest
  script:
    - cargo build --verbose --all-features

build-release:
  stage: build_release_rust
  image: rust:latest
  script:
    - cargo build --verbose --all-features --release

run-tests:
  stage: test_rust
  image: rust:latest
  script:
    - cargo test --verbose --all-features -- --nocapture
