# GitLab CI/CD configuration

# Define stages
stages:
  - build_docker_image
  - build_rust
  - test

# Docker Image CI job
Docker_Image_CI:
  stage: build_docker_image
  script:
    - docker volume create --name database
    - docker build -t serenity-discord-bot .
    - docker run -v ./database:/app/database -d --env-file .env serenity-discord-bot

# Rust job
Rust:
  stage: build_rust
  image: rust:latest
  script:
    - cargo build --verbose

# Run tests job
Run_tests:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
