# GitLab CI/CD configuration

# Define stages
stages:
  - build_rust
  - test

# Rust job
Rust:
  stage: build_rust
  image: rust:latest
  script:
    - cargo build --verbose

# Run tests job
Run_tests:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
