stages:
  - docker_build
  - build_rust
  - run_tests_rust
  - build_release_rust

variables:
  # Rust CI
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

docker_build:
  image: docker:latest
  script:
    - docker build . --file Dockerfile --tag my-image-name:$(date +%s)

build_rust:
  image: rust:latest
  script:
    - cargo build --verbose --all-features

build_release_rust:
  image: rust:latest
  script:
    - cargo build --verbose --all-features --release

run_tests_rust:
  image: rust:latest
  script:
    - cargo test --verbose --all-features -- --nocapture
