name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: RUST_BACKTRACE=full cargo build --verbose --all-features
      - name: Build Release
        run: RUST_BACKTRACE=full cargo build --verbose --all-features --release
      - name: Run tests
        run: RUST_BACKTRACE=full cargo test --verbose --all-features -- --nocapture
